name: test

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18', '20']
    env:
      ESLINT_USE_FLAT_CONFIG: false # https://eslint.org/docs/latest/use/migrate-to-9.0.0#-new-default-config-format-eslintconfigjs
    name: node.js_${{ matrix.node }}_test
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: install
        run: yarn install --frozen-lockfile

      - name: check format
        run: yarn format

      - name: lint
        run: yarn lint

      - name: test
        run: yarn test

      - name: build
        run: yarn build
